name: jokenpo
description: By Rauan Rosa.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  mobx_codegen: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/principais/logo.png
    - assets/principais/emoji_erro.png
    - assets/icones/padrao.png
    - assets/icones/papel.png
    - assets/icones/pedra.png
    - assets/icones/tesoura.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700